### PR TITLE
[WIP] Add AppVeyor builds

### PR DESCRIPTION
**Pull request by andrewda**
This PR adds AppVeyor Windows builds.

TODO:
- [ ] Get Clang [builds to work](https://ci.appveyor.com/project/andrewda/pathfinder/build/1.0.9/job/wb0o49qr45g3c2qt)
- [ ] Get Visual Studio 2015 [builds to work](https://ci.appveyor.com/project/andrewda/pathfinder/build/1.0.10/job/sn8wnncoh9vjlfth) (assuming VS 2015 is supported, @JacisNonsense?)

Closes https://github.com/GrappleRobotics/Pathfinder/issues/6

### CODE REVIEW

**Comment by JacisNonsense** [comment]
Re: Clang
Try forcing a new build that's up to date with master. I've locked the googlebench submodule to a stable release that fixes clang and gcc builds

**Comment by andrewda** [comment]
https://ci.appveyor.com/project/andrewda/pathfinder/build/1.0.12/job/lh32bae46rpeymre seems to still be failing

I didn't see any commits on master to update the googlebench submodule, though?

**Comment by JacisNonsense** [comment]
Can you rebase and try again?

**Comment by andrewda** [comment]
Still failing it seems. https://ci.appveyor.com/project/andrewda/pathfinder/build/1.0.21/job/s6y0uby607o6aj4h

**Comment by JacisNonsense** [comment]
I'll close this and cherrypick some changes into master so that I can see why it's getting hung up on MSVC depreciation warnings

**Comment by JacisNonsense** [comment]
I'm going to pull the plug and say that Clang on windows isn't supported. It's having a _lot_ of trouble. It gives endless errors no matter what I change

**Comment by ThadHouse** [comment]
Also, VS 2015 should never be used anymore. VS 2017 is 100% compatible with 2015, and is much better.

**Pull request closed without merging**
